"""Reactive dependency graph and data flow tracking."""
from __future__ import annotations

from semipy.reactivity.reactive import (
    DependencyGraph,
    SlotRef,
    add_dependency,
    add_downstream_requirement,
    clear_stale,
    get_downstream_requirements,
    get_transitive_downstream,
    get_transitive_upstream,
    is_stale,
    mark_downstream_stale,
    save_dependency_graph,
    update_slot_commit,
    load_dependency_graph,
    _get_dep_graph,
)
from semipy.reactivity.flow import (
    DataFlow,
    FLOW_ATTR,
    attach_producer_flow,
    create_flow,
    extract_flow,
    profile_output,
    _flow_from_inputs,
)
from semipy.reactivity.events import EventType, ReactiveEvent
from semipy.reactivity.observer import (
    ObserverRegistry,
    Subscription,
    load_observer_registry,
    save_observer_registry,
    subscribe,
    unsubscribe,
    emit,
    auto_subscribe,
)
from semipy.reactivity.propagation import (
    topological_sort,
    get_stale_downstream_refs,
    rebuild_spec_from_commit,
    propagate_eager,
)
from semipy.reactivity.impact import assess_impact_async

__all__ = [
    "DependencyGraph",
    "SlotRef",
    "DataFlow",
    "FLOW_ATTR",
    "attach_producer_flow",
    "add_dependency",
    "add_downstream_requirement",
    "clear_stale",
    "get_transitive_downstream",
    "get_transitive_upstream",
    "create_flow",
    "extract_flow",
    "get_downstream_requirements",
    "is_stale",
    "mark_downstream_stale",
    "profile_output",
    "save_dependency_graph",
    "update_slot_commit",
    "load_dependency_graph",
    "_get_dep_graph",
    "_flow_from_inputs",
    "EventType",
    "ReactiveEvent",
    "ObserverRegistry",
    "Subscription",
    "load_observer_registry",
    "save_observer_registry",
    "subscribe",
    "unsubscribe",
    "emit",
    "auto_subscribe",
    "topological_sort",
    "get_stale_downstream_refs",
    "rebuild_spec_from_commit",
    "propagate_eager",
    "assess_impact_async",
]
